import { useEffect, useState, type FormEvent } from "react";
import type { EmailRow } from "@postbox/shared";
import { API, api } from "./lib/api";
import { Sidebar } from "./components/Sidebar";
import { MessageTable } from "./components/MessageTable";
import { Compose } from "./components/Compose";

type User = { name: string; email: string; avatarUrl?: string | null };
export default function App() {
  const [user, setUser] = useState<User | null>(null); const [tab, setTab] = useState<"scheduled" | "sent">("scheduled"); const [compose, setCompose] = useState(false); const [rows, setRows] = useState<EmailRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [register, setRegister] = useState(false); const [authLoading, setAuthLoading] = useState(false); const [showPassword, setShowPassword] = useState(false);
  const load = async () => { try { setLoading(true); setError(""); setUser(await api<User>("/api/me")); setRows(await api<EmailRow[]>(`/api/messages?status=${tab}`)); } catch (e) { if (e instanceof Error && e.message !== "Please sign in first.") setError(e.message); else setUser(null); } finally { setLoading(false); } };
  useEffect(() => { if (!compose) load(); }, [tab, compose]);
  const submitAuth = async (event: FormEvent) => { event.preventDefault(); try { setAuthLoading(true); setError(""); const result = await api<User>(register ? "/auth/register" : "/auth/login", { method: "POST", body: JSON.stringify({ email, password }) }); setUser(result); } catch (e) { setError(e instanceof Error ? e.message : "Unable to authenticate."); } finally { setAuthLoading(false); } };
  if (!user) return <div className="login-shell"><form className="login-card" onSubmit={submitAuth}><h1>{register ? "Create account" : "Login"}</h1><a href={`${API}/auth/google`} className="google">G <span>Login with Google</span></a><p>or use your email</p><input placeholder="Email ID" type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /><input placeholder="Password" type={showPassword ? "text" : "password"} value={password} onChange={(event) => setPassword(event.target.value)} minLength={8} required /><label className="show-password"><input className="show-password-checkbox" type="checkbox" checked={showPassword} onChange={(event) => setShowPassword(event.target.checked)} /> Show password</label><button type="submit" disabled={authLoading}>{authLoading ? "Please wait..." : register ? "Sign up" : "Log in"}</button>{error && <small className="error">{error}</small>}<button type="button" className="auth-switch" onClick={() => { setRegister(!register); setError(""); }}>{register ? "Already have an account? Log in" : "Need an account? Sign up"}</button></form></div>;
  if (compose) return <Compose onBack={() => setCompose(false)} onSaved={() => { setCompose(false); setTab("scheduled"); }} email={user?.email} />;
  return <div className="app-shell"><Sidebar active={tab} onChange={setTab} onCompose={() => setCompose(true)} name={user.name} email={user.email} avatarUrl={user.avatarUrl} /><main className="inbox"><header className="topbar"><input placeholder="⌕  Search" disabled /><div className="header-user"><div className="avatar">{user.avatarUrl ? <img src={user.avatarUrl} alt="" /> : user.name.slice(0, 1)}</div><div><b>{user.name}</b><span>{user.email}</span></div></div><button className="refresh-button" onClick={load} disabled={loading} aria-label="Refresh messages">↻ <span>Refresh</span></button><button onClick={async () => { await api("/auth/logout", { method: "POST" }); setUser(null); }}>Logout</button></header>{error && <p className="error">{error} <button onClick={load}>Retry</button></p>}<MessageTable rows={rows} loading={loading} sent={tab === "sent"} /></main></div>;
}
